name: CD Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/cd-backend.yml'

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      working-directory: ./backend
      run: npm ci
      
    - name: Build
      working-directory: ./backend
      run: npm run build
      
    - name: Generate Swagger Docs
      working-directory: ./backend
      run: npm run swagger
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/petshop-backend:latest
        
    # Aqui você pode adicionar os steps de deploy para sua infraestrutura
    # Por exemplo, para AWS ECS, Digital Ocean, etc.
    
    - name: Deploy to Production
      run: echo "Add your deployment commands here"
      env:
        # Adicione as variáveis de ambiente necessárias para seu deploy
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}