name: CD Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/cd-frontend.yml'

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      working-directory: ./frontend
      run: npm ci
      
    - name: Build
      working-directory: ./frontend
      run: npm run build
      env:
        VITE_API_URL: ${{ secrets.PROD_API_URL }}
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/petshop-frontend:latest
        
    # Aqui você pode adicionar os steps de deploy para sua infraestrutura
    # Por exemplo, para Netlify, Vercel, AWS S3, etc.
    
    - name: Deploy to Production
      run: echo "Add your deployment commands here"
      env:
        # Adicione as variáveis de ambiente necessárias para seu deploy
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}